from decouple import config

REDIS_HOST = config("REDIS_HOST", "localhost")
REDIS_PORT = config("REDIS_PORT", 6379)
REDIS_AUTH = config("REDIS_AUTH")
AUTH_JWT_SECRET_KEY = config("AUTH_JWT_SECRET_KEY")
AUTH_JWT_REFRESH_SECRET_KEY = config("AUTH_JWT_REFRESH_SECRET_KEY")
AUTH_ACCESS_TOKEN_EXPIRE_MINUTES = config("AUTH_ACCESS_TOKEN_EXPIRE_MINUTES",600)  # 10*60 second =  minutes
AUTH_REFRESH_TOKEN_EXPIRE_MINUTES = config("AUTH_REFRESH_TOKEN_EXPIRE_MINUTES", 60 * 24 * 7) # 7 days
AUTH_ALGORITHM = config("AUTH_ALGORITHM", "HS256")
AUTH_CHALLENGE_SIZE = config("AUTH_CHALLENGE_SIZE",128) # size in bytes
AUTH_CHALLENGE_TIMEOUT_IN_SEC = config("AUTH_CHALLENGE_TIMEOUT_IN_SEC",60) #timeout in seconds

