apiVersion: v1
kind: Service
metadata:
  name: {{ include "cid-resolver.fullname" . }}
  labels:
    {{- include "cid-resolver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    {{- include "cid-resolver.selectorLabels" . | nindent 4 }}
