---
name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag"
        required: true
        default: ""

jobs:
  Release:
    runs-on:
      - ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ github.event.inputs.tag }}"
          message: "${{ github.event.inputs.tag }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push images
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "riddleandcode/cid-resolver:${{ github.event.inputs.tag }}"
